server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/link_shortener?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8
    username: link
    password: qwerty
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  #      ddl-auto: validate
  output:
    ansi:
      enabled:      ALWAYS
logging:
  level:
    root:           warn
    eu:
      fairyhills:   DEBUG
  pattern:
    file: '%d{yyyy.MM.dd HH:mm:ss} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy.MM.dd HH:mm:ss} %-5level [%thread] %logger{15} - %msg%n'
  file:
    path: logs
